### PR TITLE
Networking - making the stuffs work

### PR DESCRIPTION
**Pull request by jacksonwelsh**
just about everything in networking works, I also did a merge with master and didn't see anything in particular that was suss.

### CODE REVIEW

**Comment by zocat64** [comment]
Nice. I'll check over the reflection stuff and rebase the branch later today.

**Review by zocat64 — APPROVED** [review]

**Comment by zocat64** [comment]
Squash-merged in 801314b7.

**Comment by zocat64** [comment]
FYI - if you do any work on `networking` on Tuesday, you'll need to force pull from master because of the wacked out commit history.

**Comment by jacksonwelsh** [comment]
aight

**Pull request closed without merging**
